### ISSUE TITLE
Create a login button and a page for it  

### ISSUE THREAD

**Issue by chromacoder** [chromacoder/NetflixClone#5]
Create a login button on top and a login page regarding this.

**Comment by AnupeshVerma** [comment]
I'm done with the code
please assign it to me

**Comment by AnupeshVerma** [comment]
I have made a single page in which a new user can also go to sign up page

**Comment by chromacoder** [comment]
ok , go ahead for it . Make sure its responsive and do update readme file regarding this.

**Comment by chromacoder** [comment]
solve by pr  #8
